{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.952.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"customer_churn\",\"customer_feedback\",\"feature_usage\",\"onboarding\",\"support_tickets\",\"mapping_table_support_tickets\",\"mapped_feature_usage\",\"mapped_onboarding\",\"mapped_customer_feedback\",\"mapped_categories_customer_feedback\",\"dim_feature\",\"dim_signup_channel\",\"dim_plan\",\"dim_support_tickets\",\"customizations\",\"deployments\",\"apps\",\"low-code\",\"code_export\",\"credit_proxy\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "mapping_table_support_tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\mapping_table_support_tickets.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Original\", type text}, {\"Corrected\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "ca09859e-cd83-4ead-87e9-6134a054141c"
      },
      {
        "name": "mapped_feature_usage",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcvRUCC5NT08tLsnMzytWitUBChUUKDiVZuakpBaB+c75KakKrhUF+UUlYL5bZnpuooJnLlzAPbPEozQJzAwuLUhMSixOBXNCMlJzgTpTMkvygSbFAgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [corrected_feature_name = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"corrected_feature_name\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "dba7b2fe-a8de-4b88-8934-4da040692faa"
      },
      {
        "name": "mapped_onboarding",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckxRcE7MLUjMTM9TitWJVgpPTQLTQalpqUVFiTlgTnB+cmZijoJvakpmolJsLAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [signup_channel = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"signup_channel\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "c5139a2e-e21a-42db-a6ce-39439cc66f91"
      },
      {
        "name": "mapped_customer_feedback",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\mapped_customer_feedback.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Original\", type text}, {\"Corrected\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "52083061-2dd7-4d85-8365-ac06cdad68d4"
      },
      {
        "name": "mapped_categories_customer_feedback",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\mapped_categories_customer_feedback.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Category\", type text}, {\"Feedback Text\", type text}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Category\", \"feedback_text\"}, {\"Feedback Text\", \"category\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "192afad2-774e-432c-9283-7f2df674675e"
      },
      {
        "name": "customizations",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Merged Queries1\", {\"feature_usage\", \"user_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Duplicates\",{\"user_id\", \"dim_feature\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Expanded dim_feature\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Removed Columns3\",{\"user_id\", \"feature_usage_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Other Columns\", each ([feature_usage_id] = 5 or [feature_usage_id] = 6)),",
          "    #\"Inserted Sign\" = Table.AddColumn(#\"Filtered Rows1\", \"customization\", each Number.Sign([feature_usage_id]), Int64.Type),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Inserted Sign\", \"successful_design\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"successful_design\", Int64.Type}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type8\", \"failed_design\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"failed_design\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type9\", {\"user_id\"}, {{\"total_designs\", each Table.RowCount(_), Int64.Type}, {\"successful_designs\", each List.Sum([successful_design]), type nullable number}, {\"failed_designs\", each List.Sum([failed_design]), type nullable number}}),",
          "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"successful_designs\", Int64.Type}, {\"failed_designs\", Int64.Type}})",
          "in",
          "    #\"Changed Type10\""
        ],
        "kind": "m",
        "lineageTag": "58db56b5-16b6-4826-8a7b-97ff2ec8bc24"
      },
      {
        "name": "deployments",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Merged Queries1\", {\"feature_usage\", \"user_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Duplicates\",{\"user_id\", \"dim_feature\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Expanded dim_feature\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns3\", each ([feature_usage_id] = 2 or [feature_usage_id] = 3)),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"user_id\", \"feature_usage_id\", \"errors\"}),",
          "    #\"Inserted Sign\" = Table.AddColumn(#\"Removed Other Columns\", \"deployment\", each Number.Sign([feature_usage_id]), Int64.Type),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Inserted Sign\", \"successful_deployment\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"successful_deployment\", Int64.Type}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type8\", \"failed_deployment\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"failed_deployment\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type9\", {\"user_id\"}, {{\"total_deployments\", each Table.RowCount(_), Int64.Type}, {\"successful_deployments\", each List.Sum([successful_deployment]), type nullable number}, {\"failed_deployments\", each List.Sum([failed_deployment]), type nullable number}}),",
          "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"successful_deployments\", Int64.Type}, {\"failed_deployments\", Int64.Type}})",
          "in",
          "    #\"Changed Type10\""
        ],
        "kind": "m",
        "lineageTag": "9f7df0d7-4234-4801-84c1-294a60723b31"
      },
      {
        "name": "apps",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Merged Queries1\", {\"feature_usage\", \"user_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Duplicates\",{\"user_id\", \"dim_feature\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Expanded dim_feature\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns3\", each ([feature_usage_id] = 7)),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"user_id\", \"feature_usage_id\", \"errors\"}),",
          "    #\"Inserted Division\" = Table.AddColumn(#\"Removed Other Columns\", \"app_built\", each [feature_usage_id] / 7, type number),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Inserted Division\",{{\"app_built\", Int64.Type}}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type8\", \"failed_apps\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"failed_apps\", Int64.Type}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type9\", \"successful_apps\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"successful_apps\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type10\", {\"user_id\"}, {{\"total_apps\", each Table.RowCount(_), Int64.Type}, {\"successful_apps\", each List.Sum([successful_apps]), type nullable number}, {\"failed_apps\", each List.Sum([failed_apps]), type nullable number}}),",
          "    #\"Changed Type11\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"successful_apps\", Int64.Type}, {\"failed_apps\", Int64.Type}})",
          "in",
          "    #\"Changed Type11\""
        ],
        "kind": "m",
        "lineageTag": "307fe91d-c084-41c2-9672-d1cfe97ea810"
      },
      {
        "name": "low-code",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Merged Queries1\", {\"feature_usage\", \"user_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Duplicates\",{\"user_id\", \"dim_feature\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Expanded dim_feature\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns3\", each ([feature_usage_id] = 1)),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"user_id\", \"feature_usage_id\", \"errors\"}),",
          "    #\"Duplicated Column\" = Table.AddColumn(#\"Removed Other Columns\", \"AI_interaction\", each [feature_usage_id], type number),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Duplicated Column\", \"wrong_prompts\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Added Conditional Column\",{{\"wrong_prompts\", \"failed_suggestions\"}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Renamed Columns4\", \"successful_interactions\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"failed_suggestions\", Int64.Type}, {\"successful_interactions\", Int64.Type}, {\"AI_interaction\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type8\", {\"user_id\"}, {{\"total_AI_interactions\", each Table.RowCount(_), Int64.Type}, {\"failed_AI_interactions\", each List.Sum([failed_suggestions]), type nullable number}, {\"successful_AI_interactions\", each List.Sum([successful_interactions]), type nullable number}}),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"successful_AI_interactions\", Int64.Type}, {\"failed_AI_interactions\", Int64.Type}})",
          "in",
          "    #\"Changed Type9\""
        ],
        "kind": "m",
        "lineageTag": "bfe631c5-76ff-451b-9520-f40c6cda85fa"
      },
      {
        "name": "code_export",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Merged Queries1\", {\"feature_usage\", \"user_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Duplicates\",{\"user_id\", \"dim_feature\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Expanded dim_feature\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Removed Columns3\",{\"user_id\", \"feature_usage_id\", \"errors\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Other Columns\", each ([feature_usage_id] = 4)),",
          "    #\"Inserted Division\" = Table.AddColumn(#\"Filtered Rows1\", \"code_export\", each [feature_usage_id] / 4, type number),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Inserted Division\", \"successful_code_exports\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"code_export\", Int64.Type}, {\"successful_code_exports\", Int64.Type}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type8\", \"failed_code_export\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"failed_code_export\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type9\", {\"user_id\"}, {{\"total_code_exports\", each Table.RowCount(_), Int64.Type}, {\"successful_code_exports\", each List.Sum([successful_code_exports]), type nullable number}, {\"failed_code_exports\", each List.Sum([failed_code_export]), type nullable number}}),",
          "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"failed_code_exports\", Int64.Type}, {\"successful_code_exports\", Int64.Type}})",
          "in",
          "    #\"Changed Type10\""
        ],
        "kind": "m",
        "lineageTag": "2d5851a5-4c27-4231-acd1-aa0f946cabd6"
      },
      {
        "name": "credit_proxy",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Merged Queries1\", {\"feature_usage\", \"user_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Duplicates\",{\"user_id\", \"dim_feature\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Expanded dim_feature\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Removed Columns3\",{\"user_id\", \"credit_proxy_score\"}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Removed Other Columns\", {\"user_id\"}, {{\"total_credit_proxy\", each List.Sum([credit_proxy_score]), type nullable number}})",
          "in",
          "    #\"Grouped Rows\""
        ],
        "kind": "m",
        "lineageTag": "ad76930d-9419-4fa4-9fc2-efe193d72d2b"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_9f3390c2-70ed-4c89-a612-57fdb1f96b26",
        "fromColumn": "plan_type_id",
        "fromTable": "customer_churn",
        "toColumn": "plan_type_id",
        "toTable": "dim_plan"
      },
      {
        "name": "AutoDetected_4a7524a6-0c51-4989-8707-744d1b8e1ca2",
        "fromColumn": "plan_type_id",
        "fromTable": "onboarding",
        "toColumn": "plan_type_id",
        "toTable": "dim_plan"
      },
      {
        "name": "AutoDetected_7be77a0f-fb8d-4a6a-8ea7-662b98b88c39",
        "fromColumn": "signup_channel_id",
        "fromTable": "customer_churn",
        "toColumn": "signup_channel_id",
        "toTable": "dim_signup_channel"
      },
      {
        "name": "AutoDetected_d309ca59-89d9-4d89-9206-1d4d406d5574",
        "fromColumn": "signup_channel_id",
        "fromTable": "onboarding",
        "toColumn": "signup_channel_id",
        "toTable": "dim_signup_channel"
      },
      {
        "name": "AutoDetected_01125e24-1637-40f9-a0d2-5997cfe23af7",
        "fromColumn": "feature_usage_id",
        "fromTable": "feature_usage",
        "toColumn": "feature_usage_id",
        "toTable": "dim_feature"
      },
      {
        "name": "AutoDetected_664d017c-8dba-4827-b260-c18a3c774254",
        "fromColumn": "issue_type_id",
        "fromTable": "support_tickets",
        "toColumn": "issue_type_id",
        "toTable": "dim_support_tickets"
      },
      {
        "name": "dae8dd65-149a-2f2f-cd5c-6e8f7af40eac",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "user_id",
        "fromTable": "customer_feedback",
        "toColumn": "user_id",
        "toTable": "customer_churn"
      },
      {
        "name": "377413d6-ec84-eba9-f03d-40c34b79a1ec",
        "fromColumn": "user_id",
        "fromTable": "support_tickets",
        "toColumn": "user_id",
        "toTable": "customer_churn"
      },
      {
        "name": "77c0a175-a61a-5629-1c36-33945d48d65f",
        "fromColumn": "user_id",
        "fromTable": "feature_usage",
        "toColumn": "user_id",
        "toTable": "customer_churn"
      },
      {
        "name": "0d1bded5-8763-b3fb-2757-fc7bde9c65fe",
        "fromColumn": "feedback_date",
        "fromTable": "customer_feedback",
        "toColumn": "Date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "customer_churn",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c0f1f48-1cbd-4c72-a69b-8d6e79b1d1af",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "usage_frequency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8060271-bd3f-4c1d-b428-b734d6fc2234",
            "sourceColumn": "usage_frequency",
            "summarizeBy": "sum"
          },
          {
            "name": "support_contacts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "206ba5d3-80ed-4459-b78e-52064664f6dd",
            "sourceColumn": "support_contacts",
            "summarizeBy": "sum"
          },
          {
            "name": "churned_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f4e2fc13-246d-42ff-90ad-2c3f1f364262",
            "sourceColumn": "churned_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "plan_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99edb893-cf3c-4e27-9e59-c3dc14de7b72",
            "sourceColumn": "plan_type_id",
            "summarizeBy": "none"
          },
          {
            "name": "signup_channel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9ce52e7-9274-4dbb-a9c4-42a4c6eb9de3",
            "sourceColumn": "signup_channel_id",
            "summarizeBy": "none"
          },
          {
            "name": "total_designs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd045ac3-59f4-46ba-b7a1-cde9b7655b8a",
            "sourceColumn": "total_designs",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_designs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "54f9842f-17e0-4da4-9aff-488f2bb5a00a",
            "sourceColumn": "successful_designs",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_designs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fed24bdf-5879-46fe-aa8f-b7741fec743a",
            "sourceColumn": "failed_designs",
            "summarizeBy": "sum"
          },
          {
            "name": "total_deployments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5962fb40-2b2f-4982-b61d-56d02bb2e99a",
            "sourceColumn": "total_deployments",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_deployments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00191589-091f-4ed3-bcd2-ed31c86a370f",
            "sourceColumn": "successful_deployments",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_deployments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7de7903e-a07c-4a44-a40a-96c01c8bcb1d",
            "sourceColumn": "failed_deployments",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_apps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a714662-253d-40c0-be24-3ddb0571bd4d",
            "sourceColumn": "failed_apps",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_apps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a94a96b9-9518-4a7d-a05c-d9f04b6fa010",
            "sourceColumn": "successful_apps",
            "summarizeBy": "sum"
          },
          {
            "name": "total_code_exports",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d80c797-de9f-4266-81d3-806aebe04354",
            "sourceColumn": "total_code_exports",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_code_exports",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "752a2d2f-006e-4184-b9ca-1ca3516a9e72",
            "sourceColumn": "successful_code_exports",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_code_exports",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9bdfeb6b-7e8e-445f-8e86-b0ad44f02601",
            "sourceColumn": "failed_code_exports",
            "summarizeBy": "sum"
          },
          {
            "name": "total_apps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f626343-7549-425e-9a55-26507a2d5374",
            "sourceColumn": "total_apps",
            "summarizeBy": "sum"
          },
          {
            "name": "total_credit_proxy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06144053-b019-4dcb-8677-18999592664c",
            "sourceColumn": "total_credit_proxy",
            "summarizeBy": "sum"
          },
          {
            "name": "total_AI_interactions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce4d6257-6338-48e9-88c4-c9aada6377e6",
            "sourceColumn": "total_AI_interactions",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_AI_interactions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d102581c-b64d-4f0f-b671-5009c8e5793a",
            "sourceColumn": "failed_AI_interactions",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_AI_interactions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c2dfa8d3-1a98-420a-821d-b4e2fc1ca06e",
            "sourceColumn": "successful_AI_interactions",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0575a496-2d07-44e5-9e4e-cd6f1070b7ff",
        "partitions": [
          {
            "name": "customer_churn",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\customer_churn (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"plan_type\", type text}, {\"usage_frequency\", Int64.Type}, {\"support_contacts\", Int64.Type}, {\"churned_flag\", Int64.Type}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",-2,null,Replacer.ReplaceValue,{\"support_contacts\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",-1,null,Replacer.ReplaceValue,{\"support_contacts\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Replaced Value1\", {\"plan_type\"}, dim_plan, {\"plan_type\"}, \"dim_plan\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_plan\" = Table.ExpandTableColumn(#\"Merged Queries\", \"dim_plan\", {\"plan_type_id\"}, {\"plan_type_id\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Expanded dim_plan\", {\"user_id\"}, onboarding, {\"user_id\"}, \"onboarding\", JoinKind.LeftOuter),",
                "    #\"Expanded onboarding\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"onboarding\", {\"signup_channel_id\"}, {\"signup_channel_id\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded onboarding\",{\"user_id\", \"plan_type\", \"signup_channel_id\", \"usage_frequency\", \"support_contacts\", \"churned_flag\", \"plan_type_id\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns\",{\"plan_type\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Columns1\",{\"user_id\", \"plan_type_id\", \"signup_channel_id\", \"usage_frequency\", \"support_contacts\", \"churned_flag\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Reordered Columns1\", {\"user_id\"}, apps, {\"user_id\"}, \"apps\", JoinKind.LeftOuter),",
                "    #\"Expanded apps\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"apps\", {\"total_apps\", \"successful_apps\", \"failed_apps\"}, {\"total_apps\", \"successful_apps\", \"failed_apps\"}),",
                "    #\"Merged Queries3\" = Table.NestedJoin(#\"Expanded apps\", {\"user_id\"}, code_export, {\"user_id\"}, \"code_export\", JoinKind.LeftOuter),",
                "    #\"Expanded code_export\" = Table.ExpandTableColumn(#\"Merged Queries3\", \"code_export\", {\"total_code_exports\", \"successful_code_exports\", \"failed_code_exports\"}, {\"total_code_exports\", \"successful_code_exports\", \"failed_code_exports\"}),",
                "    #\"Merged Queries4\" = Table.NestedJoin(#\"Expanded code_export\", {\"user_id\"}, customizations, {\"user_id\"}, \"customizations\", JoinKind.LeftOuter),",
                "    #\"Expanded customizations\" = Table.ExpandTableColumn(#\"Merged Queries4\", \"customizations\", {\"total_designs\", \"successful_designs\", \"failed_designs\"}, {\"total_designs\", \"successful_designs\", \"failed_designs\"}),",
                "    #\"Merged Queries5\" = Table.NestedJoin(#\"Expanded customizations\", {\"user_id\"}, deployments, {\"user_id\"}, \"deployments\", JoinKind.LeftOuter),",
                "    #\"Expanded deployments\" = Table.ExpandTableColumn(#\"Merged Queries5\", \"deployments\", {\"total_deployments\", \"successful_deployments\", \"failed_deployments\"}, {\"total_deployments\", \"successful_deployments\", \"failed_deployments\"}),",
                "    #\"Merged Queries6\" = Table.NestedJoin(#\"Expanded deployments\", {\"user_id\"}, credit_proxy, {\"user_id\"}, \"credit_proxy\", JoinKind.LeftOuter),",
                "    #\"Expanded credit_proxy\" = Table.ExpandTableColumn(#\"Merged Queries6\", \"credit_proxy\", {\"total_credit_proxy\"}, {\"total_credit_proxy\"}),",
                "    #\"Merged Queries7\" = Table.NestedJoin(#\"Expanded credit_proxy\", {\"user_id\"}, #\"low-code\", {\"user_id\"}, \"low-code\", JoinKind.LeftOuter),",
                "    #\"Expanded low-code\" = Table.ExpandTableColumn(#\"Merged Queries7\", \"low-code\", {\"total_AI_interactions\", \"failed_AI_interactions\", \"successful_AI_interactions\"}, {\"total_AI_interactions\", \"failed_AI_interactions\", \"successful_AI_interactions\"})",
                "in",
                "    #\"Expanded low-code\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "customer_feedback",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f96ebbc-a667-404a-ba4a-858f25d77320",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "feedback_text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dbe56b4-7385-493d-8b7f-5600aa88f052",
            "sourceColumn": "feedback_text",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "064a3baf-5a3a-40e3-8077-268e5d61810e",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "sentiment_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3812d383-a0e6-43bf-a6ca-a5233efd1e1f",
            "sourceColumn": "sentiment_score",
            "summarizeBy": "sum"
          },
          {
            "name": "feedback_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7c32fc89-dac1-4d33-8a1c-6c2d044241d7",
            "sourceColumn": "feedback_date",
            "summarizeBy": "none"
          },
          {
            "name": "feedback_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "68faa3eb-2ac9-479e-96ff-a1b3f5c0c590",
            "sourceColumn": "feedback_time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "36c0aedd-ef2b-4dbc-9657-a6eb302a08dc",
        "partitions": [
          {
            "name": "customer_feedback",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\customer_feedback (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feedback_text\", type text}, {\"sentiment_score\", type number}, {\"category\", type text}, {\"timestamp\", type datetime}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type1\", \"Custom\", each if [feedback_text] = \"\" and [category] = \"\" then \"Remove\" else \"Keep\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each ([Custom] = \"Keep\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Custom\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns\", each true),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"user_id.1\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns1\", {\"user_id.2\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Duplicates\", {\"feedback_text\"}, mapped_customer_feedback, {\"Original\"}, \"mapped_customer_feedback\", JoinKind.LeftOuter),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id.2\", \"feedback_text\", \"mapped_customer_feedback\", \"sentiment_score\", \"category\", \"timestamp\"}),",
                "    #\"Expanded mapped_customer_feedback\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_customer_feedback\", {\"Corrected\"}, {\"mapped_customer_feedback.Corrected\"}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Expanded mapped_customer_feedback\", {\"user_id.2\"}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Removed Duplicates1\", each true),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Filtered Rows2\",{\"feedback_text\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns2\",{{\"mapped_customer_feedback.Corrected\", \"feedback_text\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns\",{\"user_id.2\", \"feedback_text\", \"category\", \"sentiment_score\", \"timestamp\"}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Reordered Columns1\", each true),",
                "    #\"Merged Queries1\" = Table.FuzzyNestedJoin(#\"Filtered Rows3\", {\"feedback_text\"}, mapped_categories_customer_feedback, {\"feedback_text\"}, \"mapped_categories_customer_feedback\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Expanded mapped_categories_customer_feedback\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"mapped_categories_customer_feedback\", {\"category\"}, {\"mapped_categories_customer_feedback.category\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Expanded mapped_categories_customer_feedback\",{\"user_id.2\", \"feedback_text\", \"category\", \"mapped_categories_customer_feedback.category\", \"sentiment_score\", \"timestamp\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Reordered Columns2\", \"Custom\", each if [category] = \"\" then \"General\" else [category], type text),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"category\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns3\",{{\"mapped_categories_customer_feedback.category\", \"category\"}, {\"user_id.2\", \"user_id\"}}),",
                "    #\"Removed Columns4\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"category\"}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Removed Columns4\",{\"user_id\", \"feedback_text\", \"Custom\", \"sentiment_score\", \"timestamp\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Reordered Columns3\",{{\"sentiment_score\", Currency.Type}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type2\", \"timestamp\", \"timestamp - Copy\"),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"timestamp\", type date}, {\"timestamp - Copy\", type time}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type3\",{{\"timestamp\", \"feedback_date\"}, {\"timestamp - Copy\", \"feedback_time\"}, {\"Custom\", \"category\"}}),",
                "    #\"Removed Duplicates2\" = Table.Distinct(#\"Renamed Columns2\", {\"feedback_text\", \"user_id\", \"category\", \"sentiment_score\"})",
                "in",
                "    #\"Removed Duplicates2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "feature_usage",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bb5aa091-f513-4592-b634-d2376e8ff06c",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "usage_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e26b172-2f9b-4589-bf87-b6bc70de7b22",
            "sourceColumn": "usage_count",
            "summarizeBy": "sum"
          },
          {
            "name": "session_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2bc2f804-169d-48c4-927b-e5652e80fc0e",
            "sourceColumn": "session_duration",
            "summarizeBy": "sum"
          },
          {
            "name": "errors",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d64c2489-fb5f-43cb-a89d-b8f95e8840ad",
            "sourceColumn": "errors",
            "summarizeBy": "sum"
          },
          {
            "name": "production_ready_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9ed724e-ee43-42f6-8bac-eeba0e96c690",
            "sourceColumn": "production_ready_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "high_customization_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb6db1e7-a228-43ef-87c1-b0fcaa9324ea",
            "sourceColumn": "high_customization_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "credit_proxy_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e46d4a4f-1305-409f-a2a9-7aca3deac4d1",
            "sourceColumn": "credit_proxy_score",
            "summarizeBy": "sum"
          },
          {
            "name": "prototype_built",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f955c2ec-2ded-4bf1-ac37-86b7057f8d93",
            "sourceColumn": "prototype_built",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_apps_built",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "59b6d189-8ec8-465d-a7ea-b4feb53b5883",
            "sourceColumn": "failed_apps_built",
            "summarizeBy": "sum"
          },
          {
            "name": "feature_usage_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad5cd131-b1f3-4dec-bd08-f61349641243",
            "sourceColumn": "feature_usage_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "279be595-a38a-4759-93e6-dd12793b461b",
        "partitions": [
          {
            "name": "feature_usage",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
                "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
                "weight = ",
                "if [feature_usage] = \"App Builder\" then 5",
                "else if [feature_usage] = \"AI Suggestions\" then 3",
                "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
                "else 1 ",
                "in (weight * [usage_count] / (1 + [errors]))),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
                "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
                "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
                "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Merged Queries1\", {\"feature_usage\", \"user_id\", \"usage_count\", \"session_duration\", \"errors\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Removed Duplicates\",{\"user_id\", \"dim_feature\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
                "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Expanded dim_feature\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"})",
                "in",
                "    #\"Removed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "onboarding",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60d77670-03ae-4bfc-85ba-d59450159ef6",
            "sourceColumn": "user_id",
            "summarizeBy": "sum"
          },
          {
            "name": "activation_time_days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eda1cc8b-1071-4351-91d1-fc79fa903da3",
            "sourceColumn": "activation_time_days",
            "summarizeBy": "sum"
          },
          {
            "name": "first_support_ticket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "7f464c90-562f-4738-92e0-94aeecf1389a",
            "sourceColumn": "first_support_ticket",
            "summarizeBy": "sum"
          },
          {
            "name": "signup_channel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "57e64294-a235-45b1-9fe2-b621b1cfe183",
            "sourceColumn": "signup_channel_id",
            "summarizeBy": "none"
          },
          {
            "name": "plan_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d72f275b-6559-492b-a927-1a540ea66a64",
            "sourceColumn": "plan_type_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90eb2972-ffd2-449c-b217-3b45d6a61d12",
        "partitions": [
          {
            "name": "onboarding",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\onboarding (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"signup_channel\", type text}, {\"activation_time_days\", type number}, {\"first_support_ticket\", type logical}, {\"plan_type\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [first_support_ticket] = false then 0 else if [first_support_ticket] = true then 1 else null, type number),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"user_id\", \"signup_channel\", \"activation_time_days\", \"first_support_ticket\", \"Custom\", \"plan_type\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"first_support_ticket\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"first_support_ticket\"}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Renamed Columns\", {\"signup_channel\"}, mapped_onboarding, {\"signup_channel\"}, \"mapped_onboarding\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"signup_channel\", \"mapped_onboarding\", \"activation_time_days\", \"first_support_ticket\", \"plan_type\"}),",
                "    #\"Expanded mapped_onboarding\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"mapped_onboarding\", {\"signup_channel\"}, {\"mapped_onboarding.signup_channel\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded mapped_onboarding\",{\"signup_channel\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"mapped_onboarding.signup_channel\", \"signup_channel\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"activation_time_days\", Int64.Type}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Changed Type2\", {\"signup_channel\"}, dim_signup_channel, {\"signup_channel\"}, \"dim_signup_channel\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_signup_channel\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"dim_signup_channel\", {\"signup_channel_id\"}, {\"signup_channel_id\"}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Expanded dim_signup_channel\",{{\"plan_type\", Text.Proper, type text}}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Capitalized Each Word\", {\"plan_type\"}, dim_plan, {\"plan_type\"}, \"dim_plan\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_plan\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"dim_plan\", {\"plan_type_id\"}, {\"plan_type_id\"}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Expanded dim_plan\",{\"signup_channel\", \"plan_type\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Removed Columns3\",{\"user_id\", \"signup_channel_id\", \"activation_time_days\", \"first_support_ticket\", \"plan_type_id\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Reordered Columns2\",{{\"first_support_ticket\", Int64.Type}}),",
                "    #\"Merged Queries3\" = Table.NestedJoin(#\"Changed Type3\", {\"signup_channel_id\"}, dim_signup_channel, {\"signup_channel_id\"}, \"dim_signup_channel\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_signup_channel1\" = Table.ExpandTableColumn(#\"Merged Queries3\", \"dim_signup_channel\", {\"signup_channel\"}, {\"signup_channel\"}),",
                "    #\"Removed Columns4\" = Table.RemoveColumns(#\"Expanded dim_signup_channel1\",{\"signup_channel\"}),",
                "    #\"Merged Queries4\" = Table.NestedJoin(#\"Removed Columns4\", {\"signup_channel_id\"}, dim_signup_channel, {\"signup_channel_id\"}, \"dim_signup_channel\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_signup_channel2\" = Table.ExpandTableColumn(#\"Merged Queries4\", \"dim_signup_channel\", {\"signup_channel\"}, {\"signup_channel\"}),",
                "    #\"Removed Columns5\" = Table.RemoveColumns(#\"Expanded dim_signup_channel2\",{\"signup_channel\"})",
                "in",
                "    #\"Removed Columns5\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "support_tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ticket_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f186c239-3267-4010-8887-4636280d15f5",
            "sourceColumn": "ticket_id",
            "summarizeBy": "sum"
          },
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc212f95-d136-4ad3-a061-384bca5eb719",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "response_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "10c1ce54-95fe-4702-99a7-310ade7ad503",
            "sourceColumn": "response_time",
            "summarizeBy": "sum"
          },
          {
            "name": "resolution_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b071223b-1289-4260-b754-fa2d214c7bd4",
            "sourceColumn": "resolution_time",
            "summarizeBy": "sum"
          },
          {
            "name": "satisfaction_rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6b9ea7d2-0c0f-4d2b-9857-7f13f5d4918f",
            "sourceColumn": "satisfaction_rating",
            "summarizeBy": "sum"
          },
          {
            "name": "issue_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5765ee4-05af-49ba-8b05-0bb106391bfa",
            "sourceColumn": "issue_type_id",
            "summarizeBy": "none"
          },
          {
            "name": "resolved_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea91dfa3-c107-4087-8a32-dc6fcd774e66",
            "sourceColumn": "resolved_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "responded_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b90e7984-26f6-477e-8171-1b84eaa9fd4b",
            "sourceColumn": "responded_to",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c32fe1ab-fe7e-4dcf-a531-d435ddb0fd50",
        "partitions": [
          {
            "name": "support_tickets",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\support_tickets (1).csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ticket_id\", type text}, {\"user_id\", type text}, {\"issue_type\", type text}, {\"response_time\", type number}, {\"resolution_time\", type number}, {\"satisfaction_rating\", type number}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"issue_type\"}, mapping_table_support_tickets, {\"Original\"}, \"mapping_table_support_tickets\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Expanded mapping_table_support_tickets\" = Table.ExpandTableColumn(#\"Merged Queries\", \"mapping_table_support_tickets\", {\"Corrected\"}, {\"mapping_table_support_tickets.Corrected\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded mapping_table_support_tickets\",{\"ticket_id\", \"user_id\", \"issue_type\", \"mapping_table_support_tickets.Corrected\", \"response_time\", \"resolution_time\", \"satisfaction_rating\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Reordered Columns\", {\"ticket_id\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"issue_type\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapping_table_support_tickets.Corrected\", \"issue_type\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"ticket_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"ticket_id.1\", \"ticket_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"ticket_id.1\", type text}, {\"ticket_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"ticket_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"ticket_id.2\", \"ticket_id\"}}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type2\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Renamed Columns2\", {\"issue_type\"}, dim_support_tickets, {\"issue_type\"}, \"dim_support_tickets\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_support_tickets\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"dim_support_tickets\", {\"issue_type_id\"}, {\"issue_type_id\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded dim_support_tickets\",{\"ticket_id\", \"user_id\", \"issue_type_id\", \"issue_type\", \"response_time\", \"resolution_time\", \"satisfaction_rating\"}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"issue_type\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Columns3\", \"resolved_flag\", each if [resolution_time] = null then null else 1),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"resolved_flag\", Int64.Type}}),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type3\", \"responded_to\", each if [response_time] = null then null else 1),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"responded_to\", Int64.Type}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type4\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Added Index\", {\"user_id\", \"ticket_id\", \"issue_type_id\", \"response_time\", \"resolution_time\", \"satisfaction_rating\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Duplicates1\",{{\"Index\", Order.Descending}}),",
                "    #\"Removed Columns4\" = Table.RemoveColumns(#\"Sorted Rows\",{\"Index\"})",
                "in",
                "    #\"Removed Columns4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_feature",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "feature_usage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "209ad0e3-71aa-4cd3-a48a-41a82bbe27f9",
            "sourceColumn": "feature_usage",
            "summarizeBy": "none"
          },
          {
            "name": "feature_usage_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7875a23-efbe-4daa-af7d-2a33e3860403",
            "sourceColumn": "feature_usage_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3c29e937-bb5a-49b3-b286-ad6bc8b5f9ea",
        "partitions": [
          {
            "name": "dim_feature",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
                "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
                "weight = ",
                "if [feature_usage] = \"App Builder\" then 5",
                "else if [feature_usage] = \"AI Suggestions\" then 3",
                "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
                "else 1 ",
                "in (weight * [usage_count] / (1 + [errors]))),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
                "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
                "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
                "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Errors\",{\"feature_usage\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"feature_usage_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_signup_channel",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "signup_channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78150a9c-7f2b-41dd-b86d-55a76dc4667d",
            "sourceColumn": "signup_channel",
            "summarizeBy": "none"
          },
          {
            "name": "signup_channel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32a119ef-d10a-47cd-bda6-d7feef748aab",
            "sourceColumn": "signup_channel_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fdb50492-5179-4c5e-8955-bbd9a504ba9c",
        "partitions": [
          {
            "name": "dim_signup_channel",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\onboarding (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"signup_channel\", type text}, {\"activation_time_days\", type number}, {\"first_support_ticket\", type logical}, {\"plan_type\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [first_support_ticket] = false then 0 else if [first_support_ticket] = true then 1 else null, type number),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"user_id\", \"signup_channel\", \"activation_time_days\", \"first_support_ticket\", \"Custom\", \"plan_type\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"first_support_ticket\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"first_support_ticket\"}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Renamed Columns\", {\"signup_channel\"}, mapped_onboarding, {\"signup_channel\"}, \"mapped_onboarding\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"signup_channel\", \"mapped_onboarding\", \"activation_time_days\", \"first_support_ticket\", \"plan_type\"}),",
                "    #\"Expanded mapped_onboarding\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"mapped_onboarding\", {\"signup_channel\"}, {\"mapped_onboarding.signup_channel\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded mapped_onboarding\",{\"signup_channel\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"mapped_onboarding.signup_channel\", \"signup_channel\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"activation_time_days\", Int64.Type}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Changed Type2\",{{\"plan_type\", Text.Proper, type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Capitalized Each Word\",{\"signup_channel\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"signup_channel_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_plan",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "plan_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f2cd470-21df-4917-a684-d575dc876369",
            "sourceColumn": "plan_type",
            "summarizeBy": "none"
          },
          {
            "name": "plan_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac8ae2ab-0d04-45c1-b818-ce4c2e3d5b4f",
            "sourceColumn": "plan_type_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "db86f85a-f8cc-4ae8-9cb8-b53b3686dc73",
        "partitions": [
          {
            "name": "dim_plan",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\onboarding (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"signup_channel\", type text}, {\"activation_time_days\", type number}, {\"first_support_ticket\", type logical}, {\"plan_type\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [first_support_ticket] = false then 0 else if [first_support_ticket] = true then 1 else null, type number),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"user_id\", \"signup_channel\", \"activation_time_days\", \"first_support_ticket\", \"Custom\", \"plan_type\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"first_support_ticket\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"first_support_ticket\"}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Renamed Columns\", {\"signup_channel\"}, mapped_onboarding, {\"signup_channel\"}, \"mapped_onboarding\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"signup_channel\", \"mapped_onboarding\", \"activation_time_days\", \"first_support_ticket\", \"plan_type\"}),",
                "    #\"Expanded mapped_onboarding\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"mapped_onboarding\", {\"signup_channel\"}, {\"mapped_onboarding.signup_channel\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded mapped_onboarding\",{\"signup_channel\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"mapped_onboarding.signup_channel\", \"signup_channel\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"activation_time_days\", Int64.Type}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Changed Type2\",{{\"plan_type\", Text.Proper, type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Capitalized Each Word\",{\"plan_type\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"plan_type_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_support_tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "issue_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0b978b3-bbbb-4cb3-9f91-0ac5a6ef4c1e",
            "sourceColumn": "issue_type",
            "summarizeBy": "none"
          },
          {
            "name": "issue_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a608f774-0045-4f84-821c-5ba476021d96",
            "sourceColumn": "issue_type_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2368fd7b-e9d7-4b6f-82e0-9061fadedb52",
        "partitions": [
          {
            "name": "dim_support_tickets",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\support_tickets (1).csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ticket_id\", type text}, {\"user_id\", type text}, {\"issue_type\", type text}, {\"response_time\", type number}, {\"resolution_time\", type number}, {\"satisfaction_rating\", type number}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"issue_type\"}, mapping_table_support_tickets, {\"Original\"}, \"mapping_table_support_tickets\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Expanded mapping_table_support_tickets\" = Table.ExpandTableColumn(#\"Merged Queries\", \"mapping_table_support_tickets\", {\"Corrected\"}, {\"mapping_table_support_tickets.Corrected\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded mapping_table_support_tickets\",{\"ticket_id\", \"user_id\", \"issue_type\", \"mapping_table_support_tickets.Corrected\", \"response_time\", \"resolution_time\", \"satisfaction_rating\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Reordered Columns\", {\"ticket_id\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"issue_type\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapping_table_support_tickets.Corrected\", \"issue_type\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"ticket_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"ticket_id.1\", \"ticket_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"ticket_id.1\", type text}, {\"ticket_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"ticket_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"ticket_id.2\", \"ticket_id\"}}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type2\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns2\",{\"issue_type\"}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates1\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"issue_type_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5814dddfaca947628b5e0e7f518edf97"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "bed5e472-903a-4a36-a104-195b6feaa64d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6a0c9cda-0714-4f99-ad6b-374ee834961b",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3ba18c66-1693-4950-b1a1-569589d5ee27",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1f69d784-c1f1-42e2-b480-4e47c78b1f33",
            "sourceColumn": "[Quarter Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5cc728b4-5a50-4d10-8d4d-7c6b9e905136",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d03e0c6f-80a3-4488-9323-d053642cb493",
            "sortByColumn": "Month",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Short Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4734a1fd-103f-486d-8d19-ffd75f9956f5",
            "sortByColumn": "Month",
            "sourceColumn": "[Short Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a299fe6e-3ea9-4164-abf2-9a383a7948d1",
            "sourceColumn": "[Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of the Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "751ef45b-e8b8-4eff-97b6-0630975a4762",
            "sourceColumn": "[Day of the Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "21f93b99-a823-4317-8cc2-1cfc1e7c592f",
            "sortByColumn": "Day of the Week",
            "sourceColumn": "[Day Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Short Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "34f91383-5733-41b8-8e30-e01fdf1368af",
            "sortByColumn": "Day of the Week",
            "sourceColumn": "[Short Day Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0947770b-637e-4579-a6d6-4f34454b7261",
            "sourceColumn": "[Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "daf81338-bd9f-4662-84be-9c33c4078000",
            "sourceColumn": "[Is Weekend]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "8f24166a-e7db-4c98-8d1f-ab56cb42f01d",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(",
                "                CALENDARAUTO(),",
                "                \"Year\", YEAR([Date]),",
                "                \"Quarter\", QUARTER([Date]),",
                "                \"Quarter Name\", FORMAT([Date], \"\\QQ\"),",
                "                \"Month\", MONTH([Date]),",
                "                \"Month Name\", FORMAT([Date], \"mmmm\"),",
                "                \"Short Month Name\", FORMAT([Date], \"mmm\"),",
                "                \"Day\", DAY([Date]),",
                "                \"Day of the Week\", WEEKDAY([Date]),",
                "                \"Day Name\", FORMAT([Date], \"dddd\"),",
                "                \"Short Day Name\", FORMAT([Date], \"ddd\"),",
                "                \"Week\", WEEKNUM([Date]),",
                "                \"Is Weekend\", IF(WEEKDAY([Date]) IN {1,7}, TRUE, FALSE)",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "91dbea3dbf074b99a37b4a3fda365832"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4afa5001-81c3-4fb2-b5e6-60589691befb",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3cd388fc-7005-4a26-8d94-f6b853223342",
        "measures": [
          {
            "name": "Total Customers",
            "expression": "COUNTROWS(customer_churn)",
            "formatString": "0",
            "lineageTag": "7fcc4320-5b36-4870-9fa3-15b3fc62c38a"
          },
          {
            "name": "Churned Customers",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Customers],",
              "    customer_churn[churned_flag] = 1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "48f87037-e6db-42c3-8b7b-7858646b2cb0"
          },
          {
            "name": "Active Customers",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Customers],",
              "    customer_churn[churned_flag] = 0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bf2acf3f-a94c-4c14-b9d1-0bbf5c80e25f"
          },
          {
            "name": "Churn Rate",
            "expression": [
              "",
              "DIVIDE([Churned Customers], [Total Customers])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b402b8e7-5a05-4b61-acd3-92944d21e60f"
          },
          {
            "name": "Retention Rate",
            "expression": [
              "",
              "DIVIDE([Active Customers], [Total Customers])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f1308f54-6279-48c5-9133-47faf48973f8"
          },
          {
            "name": "Total Failed Sessions",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(feature_usage),",
              "    FILTER(feature_usage, feature_usage[errors] > 0)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "400a1e68-c696-47c3-b92a-0bba95a4a1dd"
          },
          {
            "name": "Total Sessions",
            "expression": [
              "",
              "DISTINCTCOUNT(feature_usage[feature_usage_id])"
            ],
            "formatString": "0",
            "lineageTag": "208aac9a-3a79-43ed-be64-e8a2732a71fe"
          },
          {
            "name": "Duplicate Count",
            "expression": [
              "",
              "COUNTROWS(feature_usage) - ",
              "COUNTROWS(",
              "    SUMMARIZE(",
              "        feature_usage,",
              "        feature_usage[user_id],",
              "        feature_usage[feature_usage_id],",
              "        feature_usage[usage_count],",
              "        feature_usage[session_duration],",
              "        feature_usage[errors]",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fe2a3a32-6d2c-4deb-a48c-33215f863a0e"
          }
        ],
        "partitions": [
          {
            "name": "Table",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}