{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.952.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"customer_churn\",\"customer_feedback\",\"feature_usage\",\"total_credit_proxy\",\"onboarding\",\"support_tickets\",\"mapping_table_support_tickets\",\"mapped_feature_usage\",\"mapped_onboarding\",\"mapped_customer_feedback\",\"mapped_categories_customer_feedback\",\"customization\",\"total_apps_built\",\"deployments\",\"dim_feature\",\"dim_signup_channel\",\"dim_plan\",\"dim_support_tickets\",\"code_export\",\"low_code\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "mapping_table_support_tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\mapping_table_support_tickets.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Original\", type text}, {\"Corrected\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "ca09859e-cd83-4ead-87e9-6134a054141c"
      },
      {
        "name": "mapped_feature_usage",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcvRUCC5NT08tLsnMzytWitUBChUUKDiVZuakpBaB+c75KakKrhUF+UUlYL5bZnpuooJnLlzAPbPEozQJzAwuLUhMSixOBXNCMlJzgTpTMkvygSbFAgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [corrected_feature_name = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"corrected_feature_name\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "dba7b2fe-a8de-4b88-8934-4da040692faa"
      },
      {
        "name": "mapped_onboarding",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckxRcE7MLUjMTM9TitWJVgpPTQLTQalpqUVFiTlgTnB+cmZijoJvakpmolJsLAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [signup_channel = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"signup_channel\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "c5139a2e-e21a-42db-a6ce-39439cc66f91"
      },
      {
        "name": "mapped_customer_feedback",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\mapped_customer_feedback.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Original\", type text}, {\"Corrected\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "52083061-2dd7-4d85-8365-ac06cdad68d4"
      },
      {
        "name": "mapped_categories_customer_feedback",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\mapped_categories_customer_feedback.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Category\", type text}, {\"Feedback Text\", type text}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Category\", \"feedback_text\"}, {\"Feedback Text\", \"category\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "192afad2-774e-432c-9283-7f2df674675e"
      },
      {
        "name": "customization",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Changed Type3\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Errors\",{\"user_id\", \"feature_usage\", \"errors\", \"high_customization_flag\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Other Columns\", each ([high_customization_flag] = 1)),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Filtered Rows1\", \"successful_designs\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"successful_designs\", Int64.Type}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type8\", \"failed_designs\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"failed_designs\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type9\", {\"user_id\"}, {{\"total_designs\", each List.Sum([high_customization_flag]), type nullable number}, {\"successful_designs\", each List.Sum([successful_designs]), type nullable number}, {\"failed_designs\", each List.Sum([failed_designs]), type nullable number}})",
          "in",
          "    #\"Grouped Rows\""
        ],
        "kind": "m",
        "lineageTag": "7bc5a35b-7f82-4fab-ad57-b0127a44bea2"
      },
      {
        "name": "total_apps_built",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Errors\",{\"user_id\", \"feature_usage\", \"errors\"}),",
          "    #\"Added Custom6\" = Table.AddColumn(#\"Removed Other Columns\", \"app_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Custom6\",{{\"app_built\", Int64.Type}}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type8\", each ([app_built] = 1)),",
          "    #\"Added Custom7\" = Table.AddColumn(#\"Filtered Rows1\", \"successful_app\", each if [errors] = null then null ",
          "else if [errors] = 0 then 1 ",
          "else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Custom7\",{{\"successful_app\", Int64.Type}}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type9\", \"failed_app\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"failed_app\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type10\", {\"user_id\"}, {{\"total_apps_built\", each List.Sum([app_built]), type nullable number}, {\"failed_apps\", each List.Sum([failed_app]), type nullable number}, {\"successful_apps\", each List.Sum([successful_app]), type nullable number}}),",
          "    #\"Changed Type11\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"total_apps_built\", Int64.Type}, {\"failed_apps\", Int64.Type}, {\"successful_apps\", Int64.Type}})",
          "in",
          "    #\"Changed Type11\""
        ],
        "kind": "m",
        "lineageTag": "126fe585-9167-4e14-a3c4-0318c7ee4425"
      },
      {
        "name": "deployments",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Errors\",{\"user_id\", \"feature_usage\", \"errors\", \"production_ready_flag\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Other Columns\", each ([production_ready_flag] = 1)),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Filtered Rows1\", \"failed_deployments\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"successful_deployment\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"failed_deployments\", Int64.Type}, {\"successful_deployment\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type8\", {\"user_id\"}, {{\"total_deployments\", each List.Sum([production_ready_flag]), type nullable number}, {\"successful_deployments\", each List.Sum([successful_deployment]), type nullable number}, {\"failed_deployments\", each List.Sum([failed_deployments]), type nullable number}}),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"total_deployments\", Int64.Type}, {\"successful_deployments\", Int64.Type}})",
          "in",
          "    #\"Changed Type9\""
        ],
        "kind": "m",
        "lineageTag": "7ff481c1-cacf-40ff-9666-d7a70c0bc56c"
      },
      {
        "name": "code_export",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded dim_feature\",{\"user_id\", \"dim_feature.feature_usage_id\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns3\", each ([feature_usage_id] = 4)),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"user_id\", \"feature_usage_id\", \"errors\"}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Other Columns\", \"successful_code_exports\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"successful_code_exports\", Int64.Type}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type8\", \"failed_code_exports\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"failed_code_exports\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type9\", {\"user_id\"}, {{\"total_code_exports\", each Table.RowCount(_), Int64.Type}, {\"successful_code_exports\", each List.Sum([successful_code_exports]), type nullable number}, {\"failed_code_exports\", each List.Sum([failed_code_exports]), type nullable number}}),",
          "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"successful_code_exports\", Int64.Type}, {\"failed_code_exports\", Int64.Type}})",
          "in",
          "    #\"Changed Type10\""
        ],
        "kind": "m",
        "lineageTag": "9018e26f-b42d-4d31-b4b2-4b02cccd8389"
      },
      {
        "name": "low_code",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
          "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
          "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
          "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded dim_feature\",{\"user_id\", \"dim_feature.feature_usage_id\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
          "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
          "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns3\", each ([feature_usage_id] = 1)),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"user_id\", \"feature_usage_id\", \"errors\"}),",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Other Columns\", \"failed_low_AI_suggestions\", each if [errors] = null then null else if [errors] > 0 then 1 else 0),",
          "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"failed_low_AI_suggestions\", Int64.Type}}),",
          "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type8\", \"successful_AI_suggestions\", each if [errors] = null then null else if [errors] = 0 then 1 else 0),",
          "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"successful_AI_suggestions\", Int64.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type9\", {\"user_id\"}, {{\"total_AI_suggestions\", each Table.RowCount(_), Int64.Type}, {\"failed_AI_suggestions\", each List.Sum([failed_low_AI_suggestions]), type nullable number}, {\"successful_AI_suggestions\", each List.Sum([successful_AI_suggestions]), type nullable number}}),",
          "    #\"Changed Type10\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"successful_AI_suggestions\", Int64.Type}, {\"failed_AI_suggestions\", Int64.Type}})",
          "in",
          "    #\"Changed Type10\""
        ],
        "kind": "m",
        "lineageTag": "a405ae9e-f0fb-4a6a-8bdf-47ff23f4ed92"
      },
      {
        "name": "total_credit_proxy",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
          "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
          "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
          "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
          "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
          "weight = ",
          "if [feature_usage] = \"App Builder\" then 5",
          "else if [feature_usage] = \"AI Suggestions\" then 3",
          "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
          "else 1 ",
          "in (weight * [usage_count] / (1 + [errors]))),",
          "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Changed Type5\", {\"user_id\"}, {{\"total_credit_proxy\", each List.Sum([credit_proxy_score]), type nullable number}}),",
          "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"total_credit_proxy\", Currency.Type}})",
          "in",
          "    #\"Changed Type6\""
        ],
        "kind": "m",
        "lineageTag": "54053e19-b7f8-4996-a072-2c250d395a2c"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_9f3390c2-70ed-4c89-a612-57fdb1f96b26",
        "fromColumn": "plan_type_id",
        "fromTable": "customer_churn",
        "toColumn": "plan_type_id",
        "toTable": "dim_plan"
      },
      {
        "name": "AutoDetected_4a7524a6-0c51-4989-8707-744d1b8e1ca2",
        "fromColumn": "plan_type_id",
        "fromTable": "onboarding",
        "toColumn": "plan_type_id",
        "toTable": "dim_plan"
      },
      {
        "name": "AutoDetected_7be77a0f-fb8d-4a6a-8ea7-662b98b88c39",
        "fromColumn": "signup_channel_id",
        "fromTable": "customer_churn",
        "toColumn": "signup_channel_id",
        "toTable": "dim_signup_channel"
      },
      {
        "name": "AutoDetected_d309ca59-89d9-4d89-9206-1d4d406d5574",
        "fromColumn": "signup_channel_id",
        "fromTable": "onboarding",
        "toColumn": "signup_channel_id",
        "toTable": "dim_signup_channel"
      },
      {
        "name": "AutoDetected_01125e24-1637-40f9-a0d2-5997cfe23af7",
        "fromColumn": "feature_usage_id",
        "fromTable": "feature_usage",
        "toColumn": "feature_usage_id",
        "toTable": "dim_feature"
      },
      {
        "name": "AutoDetected_664d017c-8dba-4827-b260-c18a3c774254",
        "fromColumn": "issue_type_id",
        "fromTable": "support_tickets",
        "toColumn": "issue_type_id",
        "toTable": "dim_support_tickets"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "customer_churn",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c0f1f48-1cbd-4c72-a69b-8d6e79b1d1af",
            "sourceColumn": "user_id",
            "summarizeBy": "sum"
          },
          {
            "name": "usage_frequency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8060271-bd3f-4c1d-b428-b734d6fc2234",
            "sourceColumn": "usage_frequency",
            "summarizeBy": "sum"
          },
          {
            "name": "support_contacts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "206ba5d3-80ed-4459-b78e-52064664f6dd",
            "sourceColumn": "support_contacts",
            "summarizeBy": "sum"
          },
          {
            "name": "churned_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f4e2fc13-246d-42ff-90ad-2c3f1f364262",
            "sourceColumn": "churned_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "plan_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99edb893-cf3c-4e27-9e59-c3dc14de7b72",
            "sourceColumn": "plan_type_id",
            "summarizeBy": "none"
          },
          {
            "name": "signup_channel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9ce52e7-9274-4dbb-a9c4-42a4c6eb9de3",
            "sourceColumn": "signup_channel_id",
            "summarizeBy": "none"
          },
          {
            "name": "total_designs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd045ac3-59f4-46ba-b7a1-cde9b7655b8a",
            "sourceColumn": "total_designs",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_designs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "54f9842f-17e0-4da4-9aff-488f2bb5a00a",
            "sourceColumn": "successful_designs",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_designs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fed24bdf-5879-46fe-aa8f-b7741fec743a",
            "sourceColumn": "failed_designs",
            "summarizeBy": "sum"
          },
          {
            "name": "total_deployments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5962fb40-2b2f-4982-b61d-56d02bb2e99a",
            "sourceColumn": "total_deployments",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_deployments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00191589-091f-4ed3-bcd2-ed31c86a370f",
            "sourceColumn": "successful_deployments",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_deployments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7de7903e-a07c-4a44-a40a-96c01c8bcb1d",
            "sourceColumn": "failed_deployments",
            "summarizeBy": "sum"
          },
          {
            "name": "total_apps_built",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ffe97db-d862-4caa-a6cf-25937c0f935e",
            "sourceColumn": "total_apps_built",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_apps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a714662-253d-40c0-be24-3ddb0571bd4d",
            "sourceColumn": "failed_apps",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_apps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a94a96b9-9518-4a7d-a05c-d9f04b6fa010",
            "sourceColumn": "successful_apps",
            "summarizeBy": "sum"
          },
          {
            "name": "total_credit_proxy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "53014240-d700-4eba-bd86-4589907cfc5c",
            "sourceColumn": "total_credit_proxy",
            "summarizeBy": "sum"
          },
          {
            "name": "total_AI_suggestions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81e3ec8d-23c9-4fd6-a7e5-bbb7fdd52b17",
            "sourceColumn": "total_AI_suggestions",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_AI_suggestions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "590f1db8-32f2-4426-9c54-09bf34eaea79",
            "sourceColumn": "failed_AI_suggestions",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_AI_suggestions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6983e68a-ce7c-440f-84e9-949d294a9ec0",
            "sourceColumn": "successful_AI_suggestions",
            "summarizeBy": "sum"
          },
          {
            "name": "total_code_exports",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d80c797-de9f-4266-81d3-806aebe04354",
            "sourceColumn": "total_code_exports",
            "summarizeBy": "sum"
          },
          {
            "name": "successful_code_exports",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "752a2d2f-006e-4184-b9ca-1ca3516a9e72",
            "sourceColumn": "successful_code_exports",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_code_exports",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9bdfeb6b-7e8e-445f-8e86-b0ad44f02601",
            "sourceColumn": "failed_code_exports",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0575a496-2d07-44e5-9e4e-cd6f1070b7ff",
        "partitions": [
          {
            "name": "customer_churn",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\customer_churn (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"plan_type\", type text}, {\"usage_frequency\", Int64.Type}, {\"support_contacts\", Int64.Type}, {\"churned_flag\", Int64.Type}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",-2,null,Replacer.ReplaceValue,{\"support_contacts\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",-1,null,Replacer.ReplaceValue,{\"support_contacts\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value1\", each true),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Filtered Rows\", {\"user_id\"}, customization, {\"user_id\"}, \"customization\", JoinKind.LeftOuter),",
                "    #\"Expanded customization\" = Table.ExpandTableColumn(#\"Merged Queries\", \"customization\", {\"total_designs\"}, {\"total_designs\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Expanded customization\",{{\"total_designs\", Int64.Type}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Changed Type2\", {\"user_id\"}, customization, {\"user_id\"}, \"customization\", JoinKind.LeftOuter),",
                "    #\"Expanded customization1\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"customization\", {\"successful_designs\"}, {\"successful_designs\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Expanded customization1\",{{\"successful_designs\", Int64.Type}}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Changed Type3\", {\"user_id\"}, customization, {\"user_id\"}, \"customization\", JoinKind.LeftOuter),",
                "    #\"Expanded customization2\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"customization\", {\"failed_designs\"}, {\"failed_designs\"}),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Expanded customization2\",{{\"failed_designs\", Int64.Type}}),",
                "    #\"Merged Queries3\" = Table.NestedJoin(#\"Changed Type4\", {\"plan_type\"}, dim_plan, {\"plan_type\"}, \"dim_plan\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_plan\" = Table.ExpandTableColumn(#\"Merged Queries3\", \"dim_plan\", {\"plan_type_id\"}, {\"plan_type_id\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded dim_plan\",{\"user_id\", \"plan_type_id\", \"plan_type\", \"usage_frequency\", \"support_contacts\", \"churned_flag\", \"total_designs\", \"successful_designs\", \"failed_designs\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns\",{\"plan_type\"}),",
                "    #\"Merged Queries4\" = Table.NestedJoin(#\"Removed Columns1\", {\"user_id\"}, onboarding, {\"user_id\"}, \"onboarding\", JoinKind.LeftOuter),",
                "    #\"Expanded onboarding\" = Table.ExpandTableColumn(#\"Merged Queries4\", \"onboarding\", {\"signup_channel_id\"}, {\"signup_channel_id\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded onboarding\",{\"user_id\", \"plan_type_id\", \"signup_channel_id\", \"usage_frequency\", \"support_contacts\", \"churned_flag\", \"total_designs\", \"successful_designs\", \"failed_designs\"}),",
                "    #\"Merged Queries5\" = Table.NestedJoin(#\"Reordered Columns1\", {\"user_id\"}, deployments, {\"user_id\"}, \"deployments\", JoinKind.LeftOuter),",
                "    #\"Expanded deployments\" = Table.ExpandTableColumn(#\"Merged Queries5\", \"deployments\", {\"total_deployments\", \"successful_deployments\", \"failed_deployments\"}, {\"total_deployments\", \"successful_deployments\", \"failed_deployments\"}),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Expanded deployments\",{{\"failed_deployments\", Int64.Type}}),",
                "    #\"Merged Queries6\" = Table.NestedJoin(#\"Changed Type5\", {\"user_id\"}, total_apps_built, {\"user_id\"}, \"total_apps_built\", JoinKind.LeftOuter),",
                "    #\"Expanded total_apps_built\" = Table.ExpandTableColumn(#\"Merged Queries6\", \"total_apps_built\", {\"total_apps_built\", \"failed_apps\", \"successful_apps\"}, {\"total_apps_built.1\", \"failed_apps\", \"successful_apps\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded total_apps_built\",{{\"total_apps_built.1\", \"total_apps_built\"}}),",
                "    #\"Merged Queries7\" = Table.NestedJoin(#\"Renamed Columns1\", {\"user_id\"}, total_credit_proxy, {\"user_id\"}, \"total_credit_proxy\", JoinKind.LeftOuter),",
                "    #\"Expanded total_credit_proxy\" = Table.ExpandTableColumn(#\"Merged Queries7\", \"total_credit_proxy\", {\"total_credit_proxy\"}, {\"total_credit_proxy.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Expanded total_credit_proxy\",{{\"total_credit_proxy.1\", \"total_credit_proxy\"}}),",
                "    #\"Merged Queries8\" = Table.NestedJoin(#\"Renamed Columns2\", {\"user_id\"}, low_code, {\"user_id\"}, \"low_code\", JoinKind.LeftOuter),",
                "    #\"Expanded low_code\" = Table.ExpandTableColumn(#\"Merged Queries8\", \"low_code\", {\"total_AI_suggestions\", \"failed_AI_suggestions\", \"successful_AI_suggestions\"}, {\"total_AI_suggestions\", \"failed_AI_suggestions\", \"successful_AI_suggestions\"}),",
                "    #\"Merged Queries9\" = Table.NestedJoin(#\"Expanded low_code\", {\"user_id\"}, code_export, {\"user_id\"}, \"code_export\", JoinKind.LeftOuter),",
                "    #\"Expanded code_export\" = Table.ExpandTableColumn(#\"Merged Queries9\", \"code_export\", {\"total_code_exports\", \"successful_code_exports\", \"failed_code_exports\"}, {\"total_code_exports\", \"successful_code_exports\", \"failed_code_exports\"})",
                "in",
                "    #\"Expanded code_export\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "customer_feedback",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f96ebbc-a667-404a-ba4a-858f25d77320",
            "sourceColumn": "user_id",
            "summarizeBy": "sum"
          },
          {
            "name": "feedback_text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dbe56b4-7385-493d-8b7f-5600aa88f052",
            "sourceColumn": "feedback_text",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "064a3baf-5a3a-40e3-8077-268e5d61810e",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "sentiment_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3812d383-a0e6-43bf-a6ca-a5233efd1e1f",
            "sourceColumn": "sentiment_score",
            "summarizeBy": "sum"
          },
          {
            "name": "feedback_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7c32fc89-dac1-4d33-8a1c-6c2d044241d7",
            "sourceColumn": "feedback_date",
            "summarizeBy": "none"
          },
          {
            "name": "feedback_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "68faa3eb-2ac9-479e-96ff-a1b3f5c0c590",
            "sourceColumn": "feedback_time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "36c0aedd-ef2b-4dbc-9657-a6eb302a08dc",
        "partitions": [
          {
            "name": "customer_feedback",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\customer_feedback (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feedback_text\", type text}, {\"sentiment_score\", type number}, {\"category\", type text}, {\"timestamp\", type datetime}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type1\", \"Custom\", each if [feedback_text] = \"\" and [category] = \"\" then \"Remove\" else \"Keep\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each ([Custom] = \"Keep\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Custom\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns\", each true),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"user_id.1\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns1\", {\"user_id.2\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Duplicates\", {\"feedback_text\"}, mapped_customer_feedback, {\"Original\"}, \"mapped_customer_feedback\", JoinKind.LeftOuter),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id.2\", \"feedback_text\", \"mapped_customer_feedback\", \"sentiment_score\", \"category\", \"timestamp\"}),",
                "    #\"Expanded mapped_customer_feedback\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_customer_feedback\", {\"Corrected\"}, {\"mapped_customer_feedback.Corrected\"}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Expanded mapped_customer_feedback\", {\"user_id.2\"}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Removed Duplicates1\", each true),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Filtered Rows2\",{\"feedback_text\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns2\",{{\"mapped_customer_feedback.Corrected\", \"feedback_text\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns\",{\"user_id.2\", \"feedback_text\", \"category\", \"sentiment_score\", \"timestamp\"}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Reordered Columns1\", each true),",
                "    #\"Merged Queries1\" = Table.FuzzyNestedJoin(#\"Filtered Rows3\", {\"feedback_text\"}, mapped_categories_customer_feedback, {\"feedback_text\"}, \"mapped_categories_customer_feedback\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Expanded mapped_categories_customer_feedback\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"mapped_categories_customer_feedback\", {\"category\"}, {\"mapped_categories_customer_feedback.category\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Expanded mapped_categories_customer_feedback\",{\"user_id.2\", \"feedback_text\", \"category\", \"mapped_categories_customer_feedback.category\", \"sentiment_score\", \"timestamp\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Reordered Columns2\", \"Custom\", each if [category] = \"\" then \"General\" else [category], type text),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"category\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns3\",{{\"mapped_categories_customer_feedback.category\", \"category\"}, {\"user_id.2\", \"user_id\"}}),",
                "    #\"Removed Columns4\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"category\"}),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Removed Columns4\",{\"user_id\", \"feedback_text\", \"Custom\", \"sentiment_score\", \"timestamp\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Reordered Columns3\",{{\"sentiment_score\", Currency.Type}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type2\", \"timestamp\", \"timestamp - Copy\"),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"timestamp\", type date}, {\"timestamp - Copy\", type time}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type3\",{{\"timestamp\", \"feedback_date\"}, {\"timestamp - Copy\", \"feedback_time\"}, {\"Custom\", \"category\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "feature_usage",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bb5aa091-f513-4592-b634-d2376e8ff06c",
            "sourceColumn": "user_id",
            "summarizeBy": "sum"
          },
          {
            "name": "usage_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e26b172-2f9b-4589-bf87-b6bc70de7b22",
            "sourceColumn": "usage_count",
            "summarizeBy": "sum"
          },
          {
            "name": "session_duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2bc2f804-169d-48c4-927b-e5652e80fc0e",
            "sourceColumn": "session_duration",
            "summarizeBy": "sum"
          },
          {
            "name": "errors",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d64c2489-fb5f-43cb-a89d-b8f95e8840ad",
            "sourceColumn": "errors",
            "summarizeBy": "sum"
          },
          {
            "name": "production_ready_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9ed724e-ee43-42f6-8bac-eeba0e96c690",
            "sourceColumn": "production_ready_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "high_customization_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb6db1e7-a228-43ef-87c1-b0fcaa9324ea",
            "sourceColumn": "high_customization_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "credit_proxy_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e46d4a4f-1305-409f-a2a9-7aca3deac4d1",
            "sourceColumn": "credit_proxy_score",
            "summarizeBy": "sum"
          },
          {
            "name": "prototype_built",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f955c2ec-2ded-4bf1-ac37-86b7057f8d93",
            "sourceColumn": "prototype_built",
            "summarizeBy": "sum"
          },
          {
            "name": "failed_apps_built",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "59b6d189-8ec8-465d-a7ea-b4feb53b5883",
            "sourceColumn": "failed_apps_built",
            "summarizeBy": "sum"
          },
          {
            "name": "feature_usage_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad5cd131-b1f3-4dec-bd08-f61349641243",
            "sourceColumn": "feature_usage_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "279be595-a38a-4759-93e6-dd12793b461b",
        "partitions": [
          {
            "name": "feature_usage",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
                "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
                "weight = ",
                "if [feature_usage] = \"App Builder\" then 5",
                "else if [feature_usage] = \"AI Suggestions\" then 3",
                "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
                "else 1 ",
                "in (weight * [usage_count] / (1 + [errors]))),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
                "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
                "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
                "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Errors\", {\"feature_usage\"}, dim_feature, {\"feature_usage\"}, \"dim_feature\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_feature\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"dim_feature\", {\"feature_usage_id\"}, {\"dim_feature.feature_usage_id\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded dim_feature\",{\"user_id\", \"dim_feature.feature_usage_id\", \"feature_usage\", \"usage_count\", \"session_duration\", \"errors\", \"production_ready_flag\", \"high_customization_flag\", \"credit_proxy_score\", \"prototype_built\", \"failed_apps_built\"}),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"dim_feature.feature_usage_id\", \"feature_usage_id\"}}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"feature_usage\"})",
                "in",
                "    #\"Removed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "onboarding",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60d77670-03ae-4bfc-85ba-d59450159ef6",
            "sourceColumn": "user_id",
            "summarizeBy": "sum"
          },
          {
            "name": "activation_time_days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eda1cc8b-1071-4351-91d1-fc79fa903da3",
            "sourceColumn": "activation_time_days",
            "summarizeBy": "sum"
          },
          {
            "name": "first_support_ticket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7f464c90-562f-4738-92e0-94aeecf1389a",
            "sourceColumn": "first_support_ticket",
            "summarizeBy": "sum"
          },
          {
            "name": "signup_channel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "57e64294-a235-45b1-9fe2-b621b1cfe183",
            "sourceColumn": "signup_channel_id",
            "summarizeBy": "none"
          },
          {
            "name": "plan_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d72f275b-6559-492b-a927-1a540ea66a64",
            "sourceColumn": "plan_type_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90eb2972-ffd2-449c-b217-3b45d6a61d12",
        "partitions": [
          {
            "name": "onboarding",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\onboarding (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"signup_channel\", type text}, {\"activation_time_days\", type number}, {\"first_support_ticket\", type logical}, {\"plan_type\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [first_support_ticket] = false then 0 else if [first_support_ticket] = true then 1 else null, type number),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"user_id\", \"signup_channel\", \"activation_time_days\", \"first_support_ticket\", \"Custom\", \"plan_type\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"first_support_ticket\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"first_support_ticket\"}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Renamed Columns\", {\"signup_channel\"}, mapped_onboarding, {\"signup_channel\"}, \"mapped_onboarding\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"signup_channel\", \"mapped_onboarding\", \"activation_time_days\", \"first_support_ticket\", \"plan_type\"}),",
                "    #\"Expanded mapped_onboarding\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"mapped_onboarding\", {\"signup_channel\"}, {\"mapped_onboarding.signup_channel\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded mapped_onboarding\",{\"signup_channel\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"mapped_onboarding.signup_channel\", \"signup_channel\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"activation_time_days\", Int64.Type}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Changed Type2\", {\"signup_channel\"}, dim_signup_channel, {\"signup_channel\"}, \"dim_signup_channel\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_signup_channel\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"dim_signup_channel\", {\"signup_channel_id\"}, {\"signup_channel_id\"}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Expanded dim_signup_channel\",{{\"plan_type\", Text.Proper, type text}}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Capitalized Each Word\", {\"plan_type\"}, dim_plan, {\"plan_type\"}, \"dim_plan\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_plan\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"dim_plan\", {\"plan_type_id\"}, {\"plan_type_id\"}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Expanded dim_plan\",{\"signup_channel\", \"plan_type\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Removed Columns3\",{\"user_id\", \"signup_channel_id\", \"activation_time_days\", \"first_support_ticket\", \"plan_type_id\"})",
                "in",
                "    #\"Reordered Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "support_tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ticket_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f186c239-3267-4010-8887-4636280d15f5",
            "sourceColumn": "ticket_id",
            "summarizeBy": "sum"
          },
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc212f95-d136-4ad3-a061-384bca5eb719",
            "sourceColumn": "user_id",
            "summarizeBy": "sum"
          },
          {
            "name": "response_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "10c1ce54-95fe-4702-99a7-310ade7ad503",
            "sourceColumn": "response_time",
            "summarizeBy": "sum"
          },
          {
            "name": "resolution_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b071223b-1289-4260-b754-fa2d214c7bd4",
            "sourceColumn": "resolution_time",
            "summarizeBy": "sum"
          },
          {
            "name": "satisfaction_rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6b9ea7d2-0c0f-4d2b-9857-7f13f5d4918f",
            "sourceColumn": "satisfaction_rating",
            "summarizeBy": "sum"
          },
          {
            "name": "issue_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5765ee4-05af-49ba-8b05-0bb106391bfa",
            "sourceColumn": "issue_type_id",
            "summarizeBy": "none"
          },
          {
            "name": "resolved_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea91dfa3-c107-4087-8a32-dc6fcd774e66",
            "sourceColumn": "resolved_flag",
            "summarizeBy": "sum"
          },
          {
            "name": "responded_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b90e7984-26f6-477e-8171-1b84eaa9fd4b",
            "sourceColumn": "responded_to",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c32fe1ab-fe7e-4dcf-a531-d435ddb0fd50",
        "partitions": [
          {
            "name": "support_tickets",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\support_tickets (1).csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ticket_id\", type text}, {\"user_id\", type text}, {\"issue_type\", type text}, {\"response_time\", type number}, {\"resolution_time\", type number}, {\"satisfaction_rating\", type number}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"issue_type\"}, mapping_table_support_tickets, {\"Original\"}, \"mapping_table_support_tickets\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Expanded mapping_table_support_tickets\" = Table.ExpandTableColumn(#\"Merged Queries\", \"mapping_table_support_tickets\", {\"Corrected\"}, {\"mapping_table_support_tickets.Corrected\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded mapping_table_support_tickets\",{\"ticket_id\", \"user_id\", \"issue_type\", \"mapping_table_support_tickets.Corrected\", \"response_time\", \"resolution_time\", \"satisfaction_rating\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Reordered Columns\", {\"ticket_id\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"issue_type\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapping_table_support_tickets.Corrected\", \"issue_type\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"ticket_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"ticket_id.1\", \"ticket_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"ticket_id.1\", type text}, {\"ticket_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"ticket_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"ticket_id.2\", \"ticket_id\"}}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type2\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Renamed Columns2\", {\"issue_type\"}, dim_support_tickets, {\"issue_type\"}, \"dim_support_tickets\", JoinKind.LeftOuter),",
                "    #\"Expanded dim_support_tickets\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"dim_support_tickets\", {\"issue_type_id\"}, {\"issue_type_id\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded dim_support_tickets\",{\"ticket_id\", \"user_id\", \"issue_type_id\", \"issue_type\", \"response_time\", \"resolution_time\", \"satisfaction_rating\"}),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"issue_type\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Columns3\", \"resolved_flag\", each if [resolution_time] = null then null else 1),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"resolved_flag\", Int64.Type}}),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Changed Type3\", \"responded_to\", each if [response_time] = null then null else 1),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"responded_to\", Int64.Type}})",
                "in",
                "    #\"Changed Type4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_feature",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "feature_usage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "209ad0e3-71aa-4cd3-a48a-41a82bbe27f9",
            "sourceColumn": "feature_usage",
            "summarizeBy": "none"
          },
          {
            "name": "feature_usage_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7875a23-efbe-4daa-af7d-2a33e3860403",
            "sourceColumn": "feature_usage_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3c29e937-bb5a-49b3-b286-ad6bc8b5f9ea",
        "partitions": [
          {
            "name": "dim_feature",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\feature_usage (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"feature_name\", type text}, {\"usage_count\", Int64.Type}, {\"session_duration\", type number}, {\"errors\", Int64.Type}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"feature_name\"}, mapped_feature_usage, {\"corrected_feature_name\"}, \"mapped_feature_usage\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"feature_name\", \"mapped_feature_usage\", \"usage_count\", \"session_duration\", \"errors\"}),",
                "    #\"Expanded mapped_feature_usage\" = Table.ExpandTableColumn(#\"Reordered Columns\", \"mapped_feature_usage\", {\"corrected_feature_name\"}, {\"mapped_feature_usage.corrected_feature_name\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded mapped_feature_usage\",{\"feature_name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapped_feature_usage.corrected_feature_name\", \"feature_usage\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns1\", each true),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Custom\", each if [session_duration] > 60 then [session_duration] / 60 else [session_duration]),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Custom\",{\"Custom\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Removed Columns2\",{{\"session_duration\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"production_ready_flag\", each if [feature_usage] = \"Supabase\" or [feature_usage] = \"GitHub\" then 1 else 0),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"production_ready_flag\", Int64.Type}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"high_customization_flag\", each if [feature_usage] = \"Theme Editor\" or [feature_usage] = \"Figma Import\" then 1 else 0),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"high_customization_flag\", Int64.Type}}),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Changed Type4\", \"credit_proxy_score\", each let ",
                "weight = ",
                "if [feature_usage] = \"App Builder\" then 5",
                "else if [feature_usage] = \"AI Suggestions\" then 3",
                "else if [feature_usage] = \"GitHub\" or [feature_usage] = \"Supabase\" or [feature_usage] = \"Code Export\" then 2",
                "else 1 ",
                "in (weight * [usage_count] / (1 + [errors]))),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"credit_proxy_score\", Currency.Type}}),",
                "    #\"Added Custom4\" = Table.AddColumn(#\"Changed Type5\", \"prototype_built\", each if [feature_usage] = \"App Builder\" then 1 else 0),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Added Custom4\",{{\"prototype_built\", Int64.Type}}),",
                "    #\"Added Custom5\" = Table.AddColumn(#\"Changed Type6\", \"Custom\", each if [feature_usage] = \"App Builder\" and [errors] > 0 then 1 else 0),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom5\",{{\"Custom\", \"failed_apps_built\"}}),",
                "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"failed_apps_built\", type number}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type7\", {{\"failed_apps_built\", null}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Errors\",{\"feature_usage\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"feature_usage_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_signup_channel",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "signup_channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78150a9c-7f2b-41dd-b86d-55a76dc4667d",
            "sourceColumn": "signup_channel",
            "summarizeBy": "none"
          },
          {
            "name": "signup_channel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32a119ef-d10a-47cd-bda6-d7feef748aab",
            "sourceColumn": "signup_channel_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fdb50492-5179-4c5e-8955-bbd9a504ba9c",
        "partitions": [
          {
            "name": "dim_signup_channel",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\onboarding (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"signup_channel\", type text}, {\"activation_time_days\", type number}, {\"first_support_ticket\", type logical}, {\"plan_type\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [first_support_ticket] = false then 0 else if [first_support_ticket] = true then 1 else null, type number),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"user_id\", \"signup_channel\", \"activation_time_days\", \"first_support_ticket\", \"Custom\", \"plan_type\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"first_support_ticket\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"first_support_ticket\"}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Renamed Columns\", {\"signup_channel\"}, mapped_onboarding, {\"signup_channel\"}, \"mapped_onboarding\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"signup_channel\", \"mapped_onboarding\", \"activation_time_days\", \"first_support_ticket\", \"plan_type\"}),",
                "    #\"Expanded mapped_onboarding\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"mapped_onboarding\", {\"signup_channel\"}, {\"mapped_onboarding.signup_channel\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded mapped_onboarding\",{\"signup_channel\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"mapped_onboarding.signup_channel\", \"signup_channel\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"activation_time_days\", Int64.Type}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Changed Type2\",{{\"plan_type\", Text.Proper, type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Capitalized Each Word\",{\"signup_channel\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"signup_channel_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_plan",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "plan_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f2cd470-21df-4917-a684-d575dc876369",
            "sourceColumn": "plan_type",
            "summarizeBy": "none"
          },
          {
            "name": "plan_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac8ae2ab-0d04-45c1-b818-ce4c2e3d5b4f",
            "sourceColumn": "plan_type_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "db86f85a-f8cc-4ae8-9cb8-b53b3686dc73",
        "partitions": [
          {
            "name": "dim_plan",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\onboarding (1).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"user_id\", type text}, {\"signup_channel\", type text}, {\"activation_time_days\", type number}, {\"first_support_ticket\", type logical}, {\"plan_type\", type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [first_support_ticket] = false then 0 else if [first_support_ticket] = true then 1 else null, type number),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Conditional Column\",{\"user_id\", \"signup_channel\", \"activation_time_days\", \"first_support_ticket\", \"Custom\", \"plan_type\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"first_support_ticket\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Custom\", \"first_support_ticket\"}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Renamed Columns\", {\"signup_channel\"}, mapped_onboarding, {\"signup_channel\"}, \"mapped_onboarding\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Merged Queries\",{\"user_id\", \"signup_channel\", \"mapped_onboarding\", \"activation_time_days\", \"first_support_ticket\", \"plan_type\"}),",
                "    #\"Expanded mapped_onboarding\" = Table.ExpandTableColumn(#\"Reordered Columns1\", \"mapped_onboarding\", {\"signup_channel\"}, {\"mapped_onboarding.signup_channel\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded mapped_onboarding\",{\"signup_channel\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"mapped_onboarding.signup_channel\", \"signup_channel\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type1\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"activation_time_days\", Int64.Type}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Changed Type2\",{{\"plan_type\", Text.Proper, type text}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Capitalized Each Word\",{\"plan_type\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"plan_type_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_support_tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "issue_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0b978b3-bbbb-4cb3-9f91-0ac5a6ef4c1e",
            "sourceColumn": "issue_type",
            "summarizeBy": "none"
          },
          {
            "name": "issue_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a608f774-0045-4f84-821c-5ba476021d96",
            "sourceColumn": "issue_type_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2368fd7b-e9d7-4b6f-82e0-9061fadedb52",
        "partitions": [
          {
            "name": "dim_support_tickets",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\User\\Desktop\\Adora's CSVs\\support_tickets (1).csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ticket_id\", type text}, {\"user_id\", type text}, {\"issue_type\", type text}, {\"response_time\", type number}, {\"resolution_time\", type number}, {\"satisfaction_rating\", type number}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Changed Type\", {\"issue_type\"}, mapping_table_support_tickets, {\"Original\"}, \"mapping_table_support_tickets\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Expanded mapping_table_support_tickets\" = Table.ExpandTableColumn(#\"Merged Queries\", \"mapping_table_support_tickets\", {\"Corrected\"}, {\"mapping_table_support_tickets.Corrected\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded mapping_table_support_tickets\",{\"ticket_id\", \"user_id\", \"issue_type\", \"mapping_table_support_tickets.Corrected\", \"response_time\", \"resolution_time\", \"satisfaction_rating\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Reordered Columns\", {\"ticket_id\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Duplicates\",{\"issue_type\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"mapping_table_support_tickets.Corrected\", \"issue_type\"}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Renamed Columns\", \"ticket_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"ticket_id.1\", \"ticket_id.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"ticket_id.1\", type text}, {\"ticket_id.2\", Int64.Type}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"ticket_id.1\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"ticket_id.2\", \"ticket_id\"}}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Renamed Columns1\", \"user_id\", Splitter.SplitTextByDelimiter(\"_\", QuoteStyle.Csv), {\"user_id.1\", \"user_id.2\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"user_id.1\", type text}, {\"user_id.2\", Int64.Type}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type2\",{\"user_id.1\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Removed Columns2\",{{\"user_id.2\", \"user_id\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns2\",{\"issue_type\"}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates1\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"issue_type_id\"}})",
                "in",
                "    #\"Renamed Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}